# Generated by Django 4.1.4 on 2023-01-09 23:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("street", models.CharField(max_length=127)),
                ("number", models.CharField(max_length=10)),
                ("cep", models.CharField(max_length=10)),
                ("extra", models.CharField(max_length=100)),
            ],
        ),
    ]
