# Generated by Django 4.1.4 on 2023-01-09 23:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PaymentInfo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("number", models.CharField(max_length=20, unique=True)),
                ("security_code", models.CharField(max_length=3)),
                ("due_date", models.DateField()),
            ],
        ),
    ]
