# Generated by Django 4.1.4 on 2023-01-09 23:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ongs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("events", "0001_initial"),
        ("addresses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventvolunteers",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event",
                to="addresses.address",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="ong",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="ongs.ong",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="volunteers",
            field=models.ManyToManyField(
                related_name="event_volunteers",
                through="events.EventVolunteers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
