# Generated by Django 4.1.4 on 2023-01-05 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="address",
            name="event",
        ),
    ]
