# Generated by Django 4.1.4 on 2023-01-05 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("addresses", "0001_initial"),
        ("events", "0002_remove_address_event"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Address",
        ),
        migrations.AddField(
            model_name="event",
            name="address",
            field=models.ForeignKey(
                default=5,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event",
                to="addresses.address",
            ),
            preserve_default=False,
        ),
    ]
