# Generated by Django 4.1.4 on 2023-01-09 23:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ong",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                ("email", models.EmailField(max_length=60, unique=True)),
                ("tel", models.CharField(max_length=15)),
                ("description", models.CharField(max_length=800)),
                ("cnpj", models.CharField(max_length=14, unique=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("meio ambiente", "Meio Ambiente"),
                            ("animais", "Animais"),
                            ("assistência social", "Assistencia Social"),
                            ("cultura", "Cultura"),
                            ("saúde", "Saude"),
                            (
                                "desenvolvimento e defesa de direitos",
                                "Desenvolvimento Dd",
                            ),
                            ("habitação", "Habitacao"),
                            ("educação", "Educacao"),
                            ("pesquisa", "Pesquisa"),
                            ("outro", "Outro"),
                        ],
                        default="outro",
                        max_length=40,
                    ),
                ),
            ],
        ),
    ]
