# Generated by Django 4.1.4 on 2023-01-03 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ongs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ong",
            name="category",
            field=models.CharField(
                choices=[
                    ("meio ambiente", "Meio Ambiente"),
                    ("animais", "Animais"),
                    ("assistência social", "Assistencia Social"),
                    ("cultura", "Cultura"),
                    ("saúde", "Saude"),
                    ("desenvolvimento e defesa de direitos", "Desenvolvimento Dd"),
                    ("habitação", "Habitacao"),
                    ("educação", "Educacao"),
                    ("pesquisa", "Pesquisa"),
                    ("outro", "Outro"),
                ],
                default="outro",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="ong",
            name="user",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
