# Generated by Django 4.1.4 on 2023-01-03 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ongs", "0002_ong_category_ong_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ong",
            name="balance",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
