# Generated by Django 4.1.4 on 2023-01-05 12:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ongs", "0003_alter_ong_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="ong",
            name="users",
            field=models.ManyToManyField(
                related_name="ongs",
                through="donations.Donation",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
