# Generated by Django 4.1.4 on 2023-01-09 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ongs", "0001_initial"),
        ("donations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="donation",
            name="ong",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ongs.ong"
            ),
        ),
    ]
