# Generated by Django 4.1.4 on 2023-01-05 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0002_alter_donation_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donation",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
